CREATE TABLE "operations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "operations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" varchar(255) NOT NULL,
	"conversation_id" varchar(255) NOT NULL,
	"llm_text" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"query" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"firebase_uid" varchar(255) NOT NULL,
	"email" varchar(255),
	"display_name" varchar(255),
	"photo_url" varchar(2048),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_firebase_uid_key" UNIQUE("firebase_uid")
);
--> statement-breakpoint
ALTER TABLE "operations" ADD CONSTRAINT "operations_uid_users_firebase_uid_fk" FOREIGN KEY ("uid") REFERENCES "public"."users"("firebase_uid") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "operations_uid_created_at_idx" ON "operations" USING btree ("uid","created_at");